# Generated by Django 3.0.2 on 2020-04-18 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreeBoard',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='FreeComment',
            new_name='BoardComment',
        ),
    ]
