# Generated by Django 3.0.2 on 2020-04-18 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfis', '0002_auto_20200418_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='BoardComment',
            new_name='PostComment',
        ),
    ]
